fullnameOverride: olympics-api

replicaCount: 1

image:
  repository: maxmorhardt/olympics-api
  tag: ''
  pullPolicy: Always
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  volumes:
    - name: tmp
      mountPath: /tmp
      volumeType: emptyDir
    - name: home
      mountPath: /home/olympics
      volumeType: emptyDir
    - name: log
      mountPath: /var/log
      volumeType: emptyDir
  envFrom:
    - secretRef:
        name: olympics-api-env
  startupProbe:
    path: /health/live
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30
  readinessProbe:
    path: /health/ready
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  livenessProbe:
    path: /health/live
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: http

route:
  enabled: true
  gateway:
    name: maxstash
    namespace: envoy-gateway-system
  hostnames:
    - api.maxstash.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /olympics
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
  rateLimit:
    enabled: true
    requests: 100
    unit: Second

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

affinity:
  podAntiAffinity:
    enabled: false
    weight: 100
    topologyKey: kubernetes.io/hostname
