fullnameOverride: olympics

replicaCount: 1

image:
  repository: maxmorhardt/olympics
  tag: latest
  pullPolicy: Always
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  volumes:
    - name: tmp
      mountPath: /tmp
      volumeType: emptyDir
    - name: cache
      mountPath: /var/cache/nginx
      volumeType: emptyDir
    - name: run
      mountPath: /var/run
      volumeType: emptyDir
  startupProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30
  readinessProbe:
    path: /health
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  livenessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: http

route:
  enabled: true
  gateway:
    name: maxstash
    namespace: envoy-gateway-system
  hostnames:
    - olympics.maxstash.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
  rateLimit:
    enabled: true
    requests: 150
    unit: Second

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi

affinity:
  podAntiAffinity:
    enabled: false
    weight: 100
    topologyKey: kubernetes.io/hostname
