apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  cloudflare-ddns.py: |-
{{ .Files.Get "cloudflare-ddns.py" | indent 4 }}
  requirements.txt: |-
{{ .Files.Get "requirements.txt" | indent 4 }}
