fullnameOverride: cloudflare-cidr

schedule: '0 0 * * *'

existingSecret: cloudflare-cidr-env

image:
  repository: python
  pullPolicy: IfNotPresent
  tag: ''
  command:
    - sh
    - -c
    - |
      pip install --no-cache-dir --target=/tmp/pip -r /scripts/requirements.txt && \
      PYTHONPATH=/tmp/pip python3 /scripts/cloudflare-cidr.py

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

restartPolicy: OnFailure
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
