name: Chart CD

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: 'Helm chart name'
        required: true
        type: string
      chart_version:
        description: 'Helm chart version'
        required: false
        type: string
        default: ''
      namespace:
        description: 'Kubernetes namespace'
        required: false
        type: string
        default: 'jobs'

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-helm.yml@main
    with:
      repository: ${{ github.repository }}
      release_name: ${{ inputs.chart_name }}
      namespace: ${{ inputs.namespace }}
      chart: oci://ghcr.io/${{ github.repository_owner }}/charts/${{ inputs.chart_name }}
      chart_version: ${{ inputs.chart_version }}
    secrets: inherit
