name: Chart CI

on:
  push:
    tags:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  validate-discover-charts:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.discover.outputs.charts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Discover charts
        id: discover
        run: |
          charts=$(find charts -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "charts=${charts}" >> $GITHUB_OUTPUT
          echo "Charts: ${charts}"

  validate-charts:
    needs: validate-discover-charts
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        chart: ${{ fromJson(needs.validate-discover-charts.outputs.charts) }}
    uses: maxmorhardt/workflows/.github/workflows/ci-helm.yml@main
    with:
      repository: ${{ github.repository }}
      chart_directory: ${{ matrix.chart }}
      chart_name: ${{ matrix.chart }}
      working_directory: 'charts'
    secrets: inherit

  validate-complete:
    name: Validate Complete
    if: ${{ always() && github.event_name == 'pull_request' }}
    needs: validate-charts
    runs-on: ubuntu-latest
    steps:
      - name: Verify all validations succeeded
        env:
          RESULT: ${{ needs.validate-charts.result }}
        run: |
          echo "ci-pr result: $RESULT"
          if [ "$RESULT" != "success" ]; then
            echo "one or more chart validation jobs failed"
            exit 1
          fi

  ci-tag-parse:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      chart_name: ${{ steps.tag-parse.outputs.chart_name }}
      chart_version: ${{ steps.tag-parse.outputs.chart_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Parse tag
        id: tag-parse
        run: |
          TAG="${{ github.ref_name }}"
          CHART_NAME="${TAG%%/*}"
          CHART_VERSION="${TAG#*/}"
          echo "chart_name=${CHART_NAME}" >> $GITHUB_OUTPUT
          echo "chart_version=${CHART_VERSION}" >> $GITHUB_OUTPUT
          echo "Chart: ${CHART_NAME}, Version: ${CHART_VERSION}"

  ci:
    needs: ci-tag-parse
    if: github.event_name == 'push'
    uses: maxmorhardt/workflows/.github/workflows/ci-helm.yml@main
    with:
      repository: ${{ github.repository }}
      chart_directory: ${{ needs.ci-tag-parse.outputs.chart_name }}
      chart_name: ${{ needs.ci-tag-parse.outputs.chart_name }}
      working_directory: 'charts'
      push: ${{ github.event_name == 'push' }}
    secrets: inherit
